spring.application.name=SwiftCartApp

spring.datasource.url= jdbc:mysql://localhost:3306/ai_ecommerece

spring.datasource.username=root

spring.datasource.password=1234


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# MySQL Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8081