name: SwiftCart CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Build Spring Boot application
        working-directory: SwiftCartApp
        run: ./mvnw clean package -DskipTests

      - name: Build Docker image
        run: docker build -t swiftcart-backend:latest ./SwiftCartApp

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker tag swiftcart-backend:latest nikhilcicd/swiftcart-backend:latest

      - name: Push image to Docker Hub
        run: docker push nikhilcicd/swiftcart-backend:latest
